[build]
  publish = "./dist"
  command = "npx pnpm i --frozen-lockfile --store=node_modules/.pnpm-store && npx pnpm run build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["uuid", "jszip", "@octokit/core"]
